targets:
  $default:
    builders:
      code_gen_demo|mark_builder:
        enabled: true

builders:
   generator_app:
    import: 'package:adt/builder.dart'
    builder_factories: ['codeGeneratorBuilder']
    build_extensions: { '.dart': ['.adt.g.dart'] }
    auto_apply: root_package
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]