builders:
   generator_app:
    import: 'package:adt/builder.dart'
    builder_factories: ['adtGeneratorBuilder']
    build_extensions: { '.dart': ['.adt.g.dart'] }
    auto_apply: root_package
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]