targets:
   $default:
      builders:
         source_gen|combining_builder:
            options:
               ignore_for_file:
                  - unnecessary_brace_in_string_interps
                  - unused_element
                  - unnecessary_parenthesis

builders:
   adt:
      import: 'package:adt/builder.dart'
      builder_factories: ['adtGeneratorBuilder']
      build_extensions: { '.dart': ['.adt.g.dart'] }
      auto_apply: root_package
      build_to: cache
      applies_builders: ["source_gen|combining_builder"]