name: adt
description: A code generator for algebraic data types such as data classes and discriminated unions.
version: 0.4.0+2
homepage: https://github.com/vr19860507/adt

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  meta: ^1.2.2
  build: ^1.3.0
  analyzer: ^0.39.0
  code_builder: ^3.4.0
  source_gen: ^0.9.6
  dart_style: ^1.3.6
  adt_annotation: ^0.2.0

dev_dependencies:
  strict_analyzer: ^0.3.0