name: adt
description: A code generator for algebraic data types such as data classes and distinguishable unions.
version: 0.0.1
homepage: https://github.com/vr19860507/adt

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  adt_annotation: ^0.0.1
  code_builder: ^3.3.0
  source_gen: ^0.9.5

dev_dependencies:
  strict_analyzer: ^0.0.1