name: adt
description: A code generator for algebraic data types such as data classes and discriminated unions.
version: 0.3.0+3
homepage: https://github.com/vr19860507/adt

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.1.8
  build: ^1.3.0
  analyzer: ^0.39.10
  code_builder: ^3.3.0
  source_gen: ^0.9.5
  dart_style: ^1.3.6
  adt_annotation: ^0.1.0

dev_dependencies:
  strict_analyzer: ^0.2.0